# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d0puc3Z0kwianxE3RJF7uU2jDwTbJHSF
"""

import streamlit as st
import pandas as pd
import joblib

modelo = joblib.load('modelo_vitalfit.pkl')
scaler = joblib.load('scaler_vitalfit.pkl')

st.title('Sistema de Prediccion de Churn - VitalFit S.A.')

opcion = st.sidebar.selectbox('Seleccione Tipo de Prediccion', ['Individual', 'Masiva (Cargar CSV)'])

if opcion == 'Individual':
    st.subheader('Prediccion Individual de Socio')
    recencia = st.number_input('Recencia (Dias desde la ultima visita)', min_value=0, value=30)
    frecuencia = st.number_input('Frecuencia (Total de visitas)', min_value=1, value=10)
    valor_monetario = st.number_input('Valor Monetario Total ($)', min_value=0, value=50000)

    ticket_promedio = valor_monetario / frecuencia

    esporadico = 1 if frecuencia <= 4 else 0
    regular = 1 if 5 <= frecuencia <= 12 else 0

    if st.button('Evaluar Riesgo'):
        datos = pd.DataFrame([[recencia, frecuencia, valor_monetario, ticket_promedio, esporadico, regular]],
                             columns=['recencia', 'frecuencia', 'valor_monetario', 'ticket_promedio', 'tipo_cliente_Esporadico', 'tipo_cliente_Regular'])

        cols_num = ['recencia', 'frecuencia', 'valor_monetario', 'ticket_promedio']
        datos[cols_num] = scaler.transform(datos[cols_num])

        prediccion = modelo.predict(datos)[0]
        probabilidad = modelo.predict_proba(datos)[0][1]

        if prediccion == 1:
            st.error(f'Alerta: Alto riesgo de fuga. Probabilidad: {probabilidad * 100:.2f}%')
        else:
            st.success(f'Socio Estable. Probabilidad de fuga: {probabilidad * 100:.2f}%')

else:
    st.subheader('Prediccion Masiva de Socios')
    archivo = st.file_uploader('Cargue el archivo CSV con las metricas de los socios', type=['csv'])

    if archivo is not None:
        df = pd.read_csv(archivo)

        if st.button('Procesar Lista'):
            df_procesado = df.copy()
            df_procesado['ticket_promedio'] = df_procesado['valor_monetario'] / df_procesado['frecuencia']
            df_procesado['tipo_cliente_Esporadico'] = df_procesado['frecuencia'].apply(lambda x: 1 if x <= 4 else 0)
            df_procesado['tipo_cliente_Regular'] = df_procesado['frecuencia'].apply(lambda x: 1 if 5 <= x <= 12 else 0)

            cols_num = ['recencia', 'frecuencia', 'valor_monetario', 'ticket_promedio']
            df_procesado[cols_num] = scaler.transform(df_procesado[cols_num])

            caracteristicas = ['recencia', 'frecuencia', 'valor_monetario', 'ticket_promedio', 'tipo_cliente_Esporadico', 'tipo_cliente_Regular']

            df['Prediccion_Churn'] = modelo.predict(df_procesado[caracteristicas])
            df['Probabilidad_Fuga_%'] = (modelo.predict_proba(df_procesado[caracteristicas])[:, 1] * 100).round(2)

            st.write('Resultados del Analisis:')
            st.dataframe(df)